# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabvar_interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 535)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.parameter_area = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_area.sizePolicy().hasHeightForWidth())
        self.parameter_area.setSizePolicy(sizePolicy)
        self.parameter_area.setMaximumSize(QtCore.QSize(16777215, 50))
        self.parameter_area.setObjectName("parameter_area")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.parameter_area)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.c_slider = QtWidgets.QSlider(self.parameter_area)
        self.c_slider.setMinimum(-22)
        self.c_slider.setMaximum(21)
        self.c_slider.setProperty("value", 1)
        self.c_slider.setOrientation(QtCore.Qt.Horizontal)
        self.c_slider.setObjectName("c_slider")
        self.gridLayout_2.addWidget(self.c_slider, 0, 2, 1, 1)
        self.b_slider = QtWidgets.QSlider(self.parameter_area)
        self.b_slider.setMinimum(-22)
        self.b_slider.setMaximum(21)
        self.b_slider.setProperty("value", 1)
        self.b_slider.setOrientation(QtCore.Qt.Horizontal)
        self.b_slider.setObjectName("b_slider")
        self.gridLayout_2.addWidget(self.b_slider, 0, 1, 1, 1)
        self.a_slider = QtWidgets.QSlider(self.parameter_area)
        self.a_slider.setMinimum(-22)
        self.a_slider.setMaximum(21)
        self.a_slider.setProperty("value", 1)
        self.a_slider.setOrientation(QtCore.Qt.Horizontal)
        self.a_slider.setObjectName("a_slider")
        self.gridLayout_2.addWidget(self.a_slider, 0, 0, 1, 1)
        self.a_label = QtWidgets.QLabel(self.parameter_area)
        self.a_label.setAlignment(QtCore.Qt.AlignCenter)
        self.a_label.setObjectName("a_label")
        self.gridLayout_2.addWidget(self.a_label, 1, 0, 1, 1)
        self.b_label = QtWidgets.QLabel(self.parameter_area)
        self.b_label.setAlignment(QtCore.Qt.AlignCenter)
        self.b_label.setObjectName("b_label")
        self.gridLayout_2.addWidget(self.b_label, 1, 1, 1, 1)
        self.c_label = QtWidgets.QLabel(self.parameter_area)
        self.c_label.setAlignment(QtCore.Qt.AlignCenter)
        self.c_label.setObjectName("c_label")
        self.gridLayout_2.addWidget(self.c_label, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.parameter_area, 0, 1, 1, 1)
        self.plot_area = QtWidgets.QWidget(self.centralwidget)
        self.plot_area.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_area.sizePolicy().hasHeightForWidth())
        self.plot_area.setSizePolicy(sizePolicy)
        self.plot_area.setMinimumSize(QtCore.QSize(300, 300))
        self.plot_area.setObjectName("plot_area")
        self.gridLayout.addWidget(self.plot_area, 1, 1, 1, 1)
        self.var_tab_area = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.var_tab_area.sizePolicy().hasHeightForWidth())
        self.var_tab_area.setSizePolicy(sizePolicy)
        self.var_tab_area.setMinimumSize(QtCore.QSize(0, 100))
        self.var_tab_area.setMaximumSize(QtCore.QSize(16777215, 120))
        self.var_tab_area.setObjectName("var_tab_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.var_tab_area)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_var_frame = QtWidgets.QFrame(self.var_tab_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_var_frame.sizePolicy().hasHeightForWidth())
        self.tab_var_frame.setSizePolicy(sizePolicy)
        self.tab_var_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tab_var_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tab_var_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tab_var_frame.setObjectName("tab_var_frame")
        self.horizontalLayout.addWidget(self.tab_var_frame)
        self.tab_sign_frame = QtWidgets.QFrame(self.var_tab_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_sign_frame.sizePolicy().hasHeightForWidth())
        self.tab_sign_frame.setSizePolicy(sizePolicy)
        self.tab_sign_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tab_sign_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tab_sign_frame.setObjectName("tab_sign_frame")
        self.horizontalLayout.addWidget(self.tab_sign_frame)
        self.gridLayout.addWidget(self.var_tab_area, 2, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(140, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(140, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 136, 468))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fonction_list_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.fonction_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fonction_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fonction_list_frame.setObjectName("fonction_list_frame")
        self.verticalLayout.addWidget(self.fonction_list_frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 3, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 30))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionA_propos = QtWidgets.QAction(MainWindow)
        self.actionA_propos.setObjectName("actionA_propos")
        self.menuFichier.addAction(self.actionQuitter)
        self.menuAide.addAction(self.actionA_propos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.a_label.setText(_translate("MainWindow", "a = 1"))
        self.b_label.setText(_translate("MainWindow", "b = 1"))
        self.c_label.setText(_translate("MainWindow", "c = 1"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionA_propos.setText(_translate("MainWindow", "A propos"))
